### ISSUE TITLE
no longer works for me

### ISSUE THREAD

**Issue by Jhaego** [OIRNOIR/Remove-Discord-Mosaic#9]
hi! the plugin stopped working for me perhaps ~2 weeks ago, or some such. 

regardless, thank you for your work. base discord's solution is pretty ridiculous.

**Comment by OIRNOIR** [comment]
Unfortunately, this plugin isn't really maintained anymore since I no longer use Replugged. Personally I now use Vencord because it's more stable and almost always has working patches. I would recommend switching if you find that it makes sense for you. I would welcome a port of these fixes to this plugin through a PR if anyone would be willing to submit one, but I'm too busy IRL to make one myself. Thank you for your interest.

**Comment by Jhaego** [comment]
thank you for getting back to me, I appreciate it :-) I will try out Vencord - thanks for the shout.

**Comment by yofukashino** [comment]
> thank you for getting back to me, I appreciate it :-) I will try out Vencord - thanks for the shout.

getting fixed in 10 mins lol.
